Add api for egenmeldt-sykmelding
navikt/egenmeldt-sykmelding-backend pull request #2
Opened 2020-03-15 17:04 UTC by andreasDev

2020-03-15 17:44 UTC, tiafiring commented on api/oas3/egenmeldt-sykmelding-api.yaml
> +  - url: 'https://syfosmregister.nais.preprod.local'
Litt fort i svingene her kanskje ;)

2020-03-15 17:48 UTC, tiafiring commented on api/oas3/egenmeldt-sykmelding-api.yaml
> +        '400':
400 brukes når bruker av en eller annen grunn ikke fikk opprette sykmeldingen (f.eks. fordi brukeren allerede har vært sykmeldt i samme periode eller noe slikt)?

2020-03-15 17:49 UTC, tiafiring commented on naiserator-prod.yaml
> +      - kvPath: /azuread/data/dev/creds/egenmeldt-sykmelding-backend
dev -> prod :)

2020-03-15 17:55 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/sykmelding/api/EgenmeldtSykmeldingApi.kt
> +            val egenmeldtSykmeldingRequest = call.receive<EgenmeldtSykmeldingRequest>()
Her må vi huske å få inn tokenet også slik at vi kan hente fnr, men det antar jeg kommer :)

2020-03-15 17:55 UTC, tiafiring requested changes
Utrolig bra jobbet! 🏆 Approver den ikke siden det er litt småpirk som må fikses.

2020-03-15 18:24 UTC, andreasDev commented on api/oas3/egenmeldt-sykmelding-api.yaml
> +  - url: 'https://syfosmregister.nais.preprod.local'
litt fort ja

2020-03-15 18:24 UTC, andreasDev commented on api/oas3/egenmeldt-sykmelding-api.yaml
> +        '400':
yep, det er Bad Request

2020-03-15 18:25 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/sykmelding/api/EgenmeldtSykmeldingApi.kt
> +            val egenmeldtSykmeldingRequest = call.receive<EgenmeldtSykmeldingRequest>()
Det kommer etterhvert ja, foreløpig bare selve apiet

2020-03-16 06:31 UTC, tiafiring approved these changes

2020-03-16 06:47 UTC, MikAoJk approved these changes

2020-03-16 10:20 UTC, merged